version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo_data:/data/db # Persistent volume for MongoDB data
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: abcd # Admin username
      MONGO_INITDB_ROOT_PASSWORD: abcd # Admin password
      MONGO_INITDB_DATABASE: admin # Use admin as default database

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" # Expose Mongo-Express UI
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: abcd # MongoDB Admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: abcd # MongoDB Admin password
      ME_CONFIG_MONGODB_SERVER: mongo # MongoDB service name
      ME_CONFIG_MONGODB_AUTHDATABASE: admin # Use the admin database for authentication
    restart: always

volumes:
  mongo_data: # Define a named volume for MongoDB
